language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

# Deploy to PyPI on tags
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: basilshaji
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: basilshaji/gitflow
    python: 3.9
